version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  
  mysql:
    image: mysql
    environment:
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
      MYSQL_ROOT_PASSWORD: dbrootpassword
      MYSQL_DATABASE: dbdatabase
      MYSQL_PORT: 3306
    volumes_from:
      - datastore

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - '8081:80'

  datastore:
    image: busybox
    volumes:
      - /var/lib/mysql 

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    command: /start-dev.sh
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
      MYSQL_ROOT_PASSWORD: dbrootpassword
      MYSQL_DATABASE: dbdatabase
      MYSQL_PORT: 3306
    depends_on:
      - mysql{% if cookiecutter.use_mailhog == 'y' %}
      - mailhog{% endif %}
    links:
      - mysql
    volumes:
      - .:/app
    ports:
      - "8080:8080"

{% if cookiecutter.use_mailhog == 'y' %}
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
{% endif %}
