version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  {% if cookiecutter.use_mysql == 'y' %}
  mysql:
    image: mysql
    volumes_from:
      - datastore
    env_file: env.dev
  datastore:
    image: busybox
    volumes:
      - /var/lib/mysql
  {% endif %}

  {% if cookiecutter.use_postgres == 'y' %}
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    environment:
      - POSTGRES_USER={{cookiecutter.project_slug}}
  {% endif %}

  {% if cookiecutter.use_phpmyadmin == 'y' %}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - '8081:80'
  {% endif %}    

  django:
    build:
      context: 
      dockerfile: ./compose/django/Dockerfile-dev
    command: /start-dev.sh
    environment: 
      {% if cookiecutter.use_mysql == 'y' %}
      MYSQL_HOST: mysql{% endif %}
      {% if cookiecutter.use_postgres == 'y' %}
      POSTGRES_USER={{cookiecutter.project_slug}}{% endif %}
      USE_DOCKER=yes
    env_file: env.dev
    depends_on:
      {% if cookiecutter.use_mysql == 'y' %}
      - mysql {% endif %}
      {% if cookiecutter.use_postgres == 'y' %}
      - postgres {% endif %}
      {% if cookiecutter.use_mailhog == 'y' %}
      - mailhog {% endif %}
    links:
      - mysql
    volumes:
      - .:/app
    ports:
      - "8080:8080"

{% if cookiecutter.use_mailhog == 'y' %}
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
{% endif %}
