version: '2'

volumes:
  postgres_data: {}
  postgres_backup: {}

services:
  {% if cookiecutter.use_mysql == 'y' %}mysql:
    build: ./compose/mysql
    volumes_from:
      - datastore
    env_file: env.prod
  datastore:
    image: busybox
    volumes:
      - /var/lib/mysql{% endif %}

  {% if cookiecutter.use_postgres == 'y' %}postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    environment:
      - POSTGRES_USER={{cookiecutter.project_slug}}{% endif %}

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    user: django
    depends_on: {% if cookiecutter.use_mysql == 'y' %}
      - mysql {% endif %} {% if cookiecutter.use_postgres == 'y' %}
      - postgres {% endif %} {% if cookiecutter.use_mysql == 'y' %}
      - redis
    command: /gunicorn.sh
    env_file: env.prod

  nginx:
    build: ./compose/nginx
    depends_on:
      - django
{% if cookiecutter.use_lets_encrypt == 'y' %}
      - certbot
{% endif %}
    ports:
      - "0.0.0.0:80:80"
{% if cookiecutter.use_lets_encrypt == 'y' %}
    environment:
      - MY_DOMAIN_NAME={{ cookiecutter.domain_name }}
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt

  certbot:
    image: quay.io/letsencrypt/letsencrypt
    command: bash -c "sleep 6 && certbot certonly -n --standalone -d {{ cookiecutter.domain_name }} --text --agree-tos --email {{ cookiecutter.email }} --server https://acme-v01.api.letsencrypt.org/directory --rsa-key-size 4096 --verbose --keep-until-expiring --standalone-supported-challenges http-01"
    entrypoint: ""
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    ports:
      - "80"
      - "443"
    environment:
      - TERM=xterm
{% endif %}

  redis:
    image: redis:3.0
{% if cookiecutter.use_celery == 'y' %}
  celeryworker:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    user: django
    env_file: env.prod
    depends_on: {% if cookiecutter.use_mysql == 'y' %}
      - mysql {% endif %} {% if cookiecutter.use_postgres == 'y' %}
      - postgres {% endif %}
      - redis
    command: celery -A {{cookiecutter.project_slug}}.taskapp worker -l INFO

  celerybeat:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    user: django
    env_file: env.prod
    depends_on: {% if cookiecutter.use_mysql == 'y' %}
      - mysql {% endif %} {% if cookiecutter.use_postgres == 'y' %}
      - postgres {% endif %} 
      - redis
    command: celery -A {{cookiecutter.project_slug}}.taskapp beat -l INFO
{% endif %}
